spring:
  application:
    name: api-gateway

  ## GATEWAY CONFIGURATIONS
  cloud:
    gateway:
      routes:
        ## Service1
        - id: service1
          uri: lb://service1
          predicates:
            - Path=/api/service1/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: service1CircuitBreaker
                fallbackUri: forward:/fallback

        ## Service2
        - id: service2
          uri: lb://service2
          predicates:
            - Path=/api/service2/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: service2CircuitBreaker
                fallbackUri: forward:/fallback

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      service1CircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5000ms
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        eventConsumerBufferSize: 5

      service2CircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 1000ms
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        eventConsumerBufferSize: 5


